### PR TITLE
Remove the previous "Undo" option before displaying the new one

### LINKED ISSUE #353: Bug: Remove the previous "Undo" option before displaying the new one
### Description

When swiping to delete multiple alarms simultaneously, the application does not remove the previous "Undo" option before displaying the new one. This behavior can lead to confusion as users may unintentionally trigger the wrong undo action.

### Steps to Reproduce:
1. Swipe to delete one alarm.
2. Quickly swipe to delete another alarm before the previous undo option disappears.

### Expected Behavior
The application should remove the previous "Undo" option when a new alarm is swiped for deletion, ensuring a clear and accurate undo action.

### Current Behavior
The previous "Undo" option persists when swiping to delete multiple alarms simultaneously.

please assign this to me

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Deepanshuigtm**
### Description
When swiping to delete multiple alarms simultaneously, the application does not remove the previous "Undo" option before displaying the new one. This behavior can lead to confusion as users may unintentionally trigger the wrong undo action.

### Proposed Changes
Added a check to clear the current Snackbar if it is open before displaying a new one

## Fixes #353 

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

File: lib/app/modules/home/controllers/home_controller.dart [hunk 1]
```diff
@@ -528,7 +528,7 @@ class HomeController extends GetxController {
       await IsarDb.deleteAlarm(alarm.isarId);
     }
 
-    // Display snackbar
+    Get.back();
```
Comment (MarkisDev) [inline lib/app/modules/home/controllers/home_controller.dart:531]: Might be a better idea to use GetX to check if snackbars are active using `isSnackbarOpen` and close it using `closeAllSnackBars`

**Review by MarkisDev — CHANGES_REQUESTED** [review]

**Review by Deepanshuigtm — COMMENTED** [review]
used a check method issnackbar open then close all snackbar please review

**Comment by superiorsd10** [comment]
Hello @Deepanshuigtm 👋

I hope you're doing well. I was working on issue #370 and I just wanna ask if there is any particular reason for changing the snack bar UI.

Thank you,

**Comment by Deepanshuigtm** [comment]
Hello  @superiorsd10 

I initially used Get.snackbar for the snackbar, but later, I modified it. I believe it utilized default themes, which might be the reason for the change in the snackbar UI.
