### PR TITLE
Bug: AM and PM in the addOrUpdateAlarm the text is not fully completed

### LINKED ISSUE #668: Bug: AM and PM in the addOrUpdateAlarm the text is not fully completed
### Description
in the small-sized phone, there is a bug in the screen where we addOrUpdate alarm. AM and PM are shown as A and P 

### Screenshots

https://github.com/user-attachments/assets/683e304b-9fee-4625-9c7c-3d9456e0a5aa

### PR DESCRIPTION
**Pull request by mahendra-918**
### Description
the bug is sloved 

### Proposed Changes
updated the add_or_update_alarm_view.dart 

## Fixes #668

Replace `668` with the issue number which is fixed in this PR

## Screenshots
https://github.com/user-attachments/assets/52242ef5-da14-413b-99aa-16d45d62621c
## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by mahendra-918** [comment]
hi @MarkisDev can you please review this

File: lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart [hunk 1]
```diff
@@ -42,6 +42,10 @@ class AddOrUpdateAlarmView extends GetView<AddOrUpdateAlarmController> {
   final InputTimeController inputTimeController =
       Get.put(InputTimeController());
   final SettingsController settingsController = Get.find<SettingsController>();
+  double getFontSize(BuildContext context) {
```
Comment (MarkisDev) [inline lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart:45]: Ideally, a function like this should sit within utils so we can reuse it in multiple places.

**Review by MarkisDev — CHANGES_REQUESTED** [review]

**Comment by mahendra-918** [comment]
hii @MarkisDev can you please review this now 
i added the funtion(getFontSize) in utils.dart and removed the function in add_or_update_alarm.dart
