### PR TITLE
Alarm swipe delete confirmation button(No) color fix(Red)

### LINKED ISSUE #506: Bug: Alarm swipe delete confirmation button(No) color fixed to (Red)
### Description

The confirmation dialog in swipe to delete alarm had a green No button which is now changed to red.

### Screenshots

Screenshot_20240311_020357

### PR DESCRIPTION
**Pull request by AryanSarafDev**
### Description
alarm swipe delete confirmation button(No) color fix(Red)

### Proposed Changes
Color changed from kprimary color to Colors.red

## Screenshots

Screenshot_20240311_020357

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

File: lib/app/modules/home/views/home_view.dart [hunk 1]
```diff
@@ -1412,12 +1412,12 @@ class HomeView extends GetView<HomeController> {
                     Get.back(result: false);
                   },
                   style: ButtonStyle(
```
Comment (MarkisDev) [inline lib/app/modules/home/views/home_view.dart:1414]: Let's style this similar to the cancel button in unlink account.

**Review by MarkisDev — CHANGES_REQUESTED** [review]
