### PR TITLE
fix: resolve text overflow in WeatherTile for small, medium, and large screens

### LINKED ISSUE #676: Bug: Text Overflow in Weather Condition Section
### Description

The text in the "Weather Condition" section is overflowing to the right, making it difficult to read.

# Expected Behavior:
The text should fit within the container without overflowing.

# Actual Behavior:
The text is overflowing to the right, making it partially unreadable.

note : - this bug is coming for all types of device

### Screenshots

Image

LARGE PHONE 

Image
MEDIUM PHONE 

Image
SMALL PHONE

### PR DESCRIPTION
**Pull request by mahendra-918**
### Description
This PR fixes the text overflow issue in the `WeatherTile` widget. The issue occurred on small, medium, and large screens where the weather condition text would overflow and become unreadable and This PR removes the unnecessary request for location permission when selecting weather conditions for alarms. The weather condition feature does not require location data, and requesting location permissions can negatively impact the user experience.

### Proposed Changes
- Wrapped the `Text` widget in the `trailing` property with `Flexible` to ensure it respects available space.
- Used `FittedBox` for the title to scale down the text if necessary.
- Added constraints to the `ListTile` to prevent overflow.
- Tested the changes on multiple devices to ensure responsiveness.

## Screenshots

https://github.com/user-attachments/assets/d6247460-6dc1-4c27-9c92-7d0a859e96b0

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by mahendra-918** [comment]
Hi @MarkisDev can review this PR

File: lib/app/modules/addOrUpdateAlarm/views/weather_tile.dart [hunk 1]
```diff
@@ -7,407 +7,249 @@ import 'package:ultimate_alarm_clock/app/utils/utils.dart';
...
-                                    style: Theme.of(context)
-                                        .textTheme
-                                        .bodySmall!
-                                        .copyWith(fontSize: 15),
-                                  ),
-                                ],
+                            Padding(
+                              padding: const EdgeInsets.only(top: 15.0),
+                              child: Text(
+                                // 'This feature will automatically'
```
Comment (MarkisDev) [inline lib/app/modules/addOrUpdateAlarm/views/weather_tile.dart:117]: We can remove this commented part

**Review by MarkisDev — CHANGES_REQUESTED** [review]

**Review by MarkisDev — APPROVED** [review]
