### PR TITLE
Fix alarm deletion issues: Prevent update after deletion when dismissing alarms

### LINKED ISSUE #798: Bug: Alarm is not deleted when deleteAfterGoesOff is enabled
### Description
The alarm is not deleted from the home screen after it rings and `deleteAfterGoesOff` is enabled. Also, if the user tries to use that alarm again it does not ring. 

### Video of the issue:

https://github.com/user-attachments/assets/3e594c32-9f77-44b8-b987-77f2c0e2e14c

### Debug logs
After it gets deleted, 2 update logs show up:

Image

### PR DESCRIPTION
**Pull request by mahendra-918**
### Description
When an alarm with deleteAfterGoesOff enabled is dismissed, the system was correctly initiating deletion but then continuing to update the same alarm, causing inconsistent behavior. Log analysis showed "Alarm deleted" followed immediately by "Alarm updated" messages.
Added early returns after successful alarm deletion to prevent execution from continuing to the update logic
Added proper try/catch blocks around database operations
Ensured awaiting of async operations to prevent race conditions

### Proposed Changes
Fixed alarm deletion logic to ensure one-time alarms with deleteAfterGoesOff enabled are properly deleted when dismissed
Added early returns after deletion operations to prevent conflicting database operations
Ensured proper asynchronous execution with await keywords on database operations

## Screenshots

https://github.com/user-attachments/assets/96ab43dc-79a1-461b-a72e-c485642f11d2

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by mahendra-918** [comment]
Hi @MarkisDev can you please review this PR

File: lib/app/modules/alarmRing/controllers/alarm_ring_controller.dart [hunk 1]
```diff
@@ -332,16 +322,81 @@ class AlarmControlController extends GetxController {
...
+              await FirestoreDb.deleteOneTimeAlarm(
+                currentlyRingingAlarm.value.ownerId,
+                currentlyRingingAlarm.value.firestoreId,
+              );
+              print("COMPLETED deleting shared alarm");
+            } catch (e) {
+              print("ERROR deleting shared alarm: $e");
+            }
+            _subscription.cancel();
+            _currentTimeTimer?.cancel();
```
Comment (MarkisDev) [inline lib/app/modules/alarmRing/controllers/alarm_ring_controller.dart:346]: We don't need to repeat this set of code as it has to execute regardless of the condition.

**Review by MarkisDev — CHANGES_REQUESTED** [review]

**Review by MarkisDev — APPROVED** [review]
